CREATE TABLE Region (
    ID INTEGER PRIMARY KEY,
    Nom TEXT NOT NULL
);
CREATE TABLE Serveur (
    ID INTEGER PRIMARY KEY,
    Nom TEXT NOT NULL,
    RegionID INTEGER NOT NULL,
    FOREIGN KEY (RegionID) REFERENCES Region(ID)
);
CREATE TABLE Role (
    ID INTEGER PRIMARY KEY,
    Nom TEXT NOT NULL UNIQUE
);
CREATE TABLE Classe (
    ID INTEGER PRIMARY KEY,
    Image TEXT,
    RoleID INTEGER NOT NULL, Nom TEXT NOT NULL DEFAULT 'Inconnu',
    FOREIGN KEY (RoleID) REFERENCES Role(ID)
);
CREATE TABLE Joueur (
    ID INTEGER PRIMARY KEY,
    Pseudo TEXT NOT NULL,
    ServeurID INTEGER NOT NULL, Password TEXT,
    FOREIGN KEY (ServeurID) REFERENCES Serveur(ID)
);
CREATE TABLE LienExterne (
    ID INTEGER PRIMARY KEY,
    URL TEXT NOT NULL,
    JoueurID INTEGER NOT NULL,
    FOREIGN KEY (JoueurID) REFERENCES Joueur(ID)
);
CREATE TABLE Classe_Joueur (
    ID INTEGER PRIMARY KEY,
    JoueurID INTEGER NOT NULL,
    ClasseID INTEGER NOT NULL,
    Niveau INTEGER NOT NULL,
    FOREIGN KEY (JoueurID) REFERENCES Joueur(ID),
    FOREIGN KEY (ClasseID) REFERENCES Classe(ID)
);
CREATE TABLE Difficulté (
    ID INTEGER PRIMARY KEY,
    Nom TEXT NOT NULL,
    NombreJoueur INTEGER NOT NULL
);
CREATE TABLE Combat (
    ID INTEGER PRIMARY KEY,
    Nom TEXT NOT NULL,
    Niveau INTEGER NOT NULL,
    ILVL INTEGER NOT NULL,
    DifficultéID INTEGER NOT NULL,
    FOREIGN KEY (DifficultéID) REFERENCES Difficulté(ID)
);
CREATE TABLE Raidplan (
    ID INTEGER PRIMARY KEY,
    Nom TEXT NOT NULL,
    URL TEXT NOT NULL,
    CombatID INTEGER NOT NULL,
    FOREIGN KEY (CombatID) REFERENCES Combat(ID)
);
CREATE TABLE Raid (
    ID INTEGER PRIMARY KEY,
    Heure TEXT NOT NULL, -- format ISO 8601
    OrganisateurID INTEGER NOT NULL,
    CombatID INTEGER NOT NULL,
    RaidplanID INTEGER NOT NULL,
    FOREIGN KEY (OrganisateurID) REFERENCES Joueur(ID),
    FOREIGN KEY (CombatID) REFERENCES Combat(ID),
    FOREIGN KEY (RaidplanID) REFERENCES Raidplan(ID)
);
CREATE TABLE Raid_Role (
    ID INTEGER PRIMARY KEY,
    RaidID INTEGER NOT NULL,
    RoleID INTEGER NOT NULL,
    NombreJoueur INTEGER NOT NULL,
    FOREIGN KEY (RaidID) REFERENCES Raid(ID),
    FOREIGN KEY (RoleID) REFERENCES Role(ID)
);
CREATE TABLE Joueur_Raid (
    ID INTEGER PRIMARY KEY,
    JoueurID INTEGER NOT NULL,
    RaidID INTEGER NOT NULL,
    ClasseID INTEGER NOT NULL,
    FOREIGN KEY (JoueurID) REFERENCES Joueur(ID),
    FOREIGN KEY (RaidID) REFERENCES Raid(ID),
    FOREIGN KEY (ClasseID) REFERENCES Classe(ID)
);
